--[[
   The copyright to the computer program(s) herein is the property of
   Invetech Pty Ltd, Australia. This file is subject to the terms and
   conditions found in the 'IMPLicense.txt' file included with this
   source code package.
--]]

--! Autogenerated script for raising alerts. Do not modify by hand.

local alerts = require("lua_alerts")

local CustomAlerts = { }

-- @brief Raise alert and call error() for: An unknown Safety Critical severity error has occurred while reading an interface property. The software will need to be restarted.
function CustomAlerts.RaisePropertyErrorSafetyCriticalAndExit()
    local reportId = alerts.RaiseSafetyCriticalSeverityAlert(30006)
    error("Raised alert of severity SafetyCritical with reportId "..tostring(reportId))
end

-- @brief clear alert convenience method
function CustomAlerts.ClearAlert(reportedId)
    alerts.ClearAlert(reportedId)
end


return CustomAlerts
